runtime: python39
entrypoint: gunicorn -b :$PORT app:app

env_variables:
  GOOGLE_CLOUD_PROJECT: "proiectcc-419616"
handlers:
- url: /.*
  script: auto

env: standard
instance_class: F1



automatic_scaling:
  min_instances: 1
  max_instances: 2
resources:
  cpu: 1
  memory_gb: 0.5
  disk_size_gb: 10
